### ISSUE TITLE
I would like to consult, you successfully set up radius server?

### ISSUE THREAD

**Issue by bbhxwl** [vforteli/RadiusServer#1]
I want to find C # development of the radius server, do you have?

**Comment by vforteli** [comment]
https://github.com/vforteli/RadiusServerService contains an implementation used in production, however it is made according to our specific requirements, so it will not be very useful without modification.

**Comment by bbhxwl** [comment]
I downloaded a lot of errors, I am Chinese, Chinese information is very little, I hope you can help me, you can run the project.

**Comment by bbhxwl** [comment]
![qq 20170516032434](https://cloud.githubusercontent.com/assets/26525599/26075299/51f7133a-39e7-11e7-8bcf-17aecf7feeab.png)

**Comment by vforteli** [comment]
Yes, so those references are specific to our implementation and should be removed.
https://github.com/vforteli/RadiusServerService/tree/Base this branch is a cleaned up version using less references and only a basic mock packet handler.

**Comment by bbhxwl** [comment]
C # this little information in this area.
![qq 20170516034650](https://cloud.githubusercontent.com/assets/26525599/26076195/828fe3ca-39ea-11e7-9899-0f78bd6bc0fb.png)

**Comment by bbhxwl** [comment]
Can you give me radiusserver.dll? I think the most important may be this, I try.

**Comment by vforteli** [comment]
Oh, that can be removed, leftovers from a clickonce installation project.

**Comment by vforteli** [comment]
radiusserver.dll is built from this project https://github.com/vforteli/RadiusServer and has to be referenced by radiusserverservice

**Comment by bbhxwl** [comment]
I obviously have the nuget package, but still can not run. Hey
 
![qq 20170516035731](https://cloud.githubusercontent.com/assets/26525599/26076737/4d2b3750-39ec-11e7-8e4a-18be3e35efba.png)

**Comment by vforteli** [comment]
You will have to enable nuget package restore (right click the solution and it should be there). Also note that the projects target .Net 4.6.2

**Comment by bbhxwl** [comment]
I built a new project, the code copied to the new project which is running, but there will be a mistake, the path access was rejected?
Do you have a mailbox? I sent you my project, you look, I did not use the service, but the use of winform


![qq 20170516035731](https://cloud.githubusercontent.com/assets/26525599/26077983/8eccff8c-39f0-11e7-9107-babe95d89ce8.png)

**Comment by bbhxwl** [comment]
Made the wrong picture

**Comment by bbhxwl** [comment]
![qq 20170516042548](https://cloud.githubusercontent.com/assets/26525599/26078311/a537218e-39f1-11e7-9ddf-01fc8930748e.png)

**Comment by bbhxwl** [comment]
Chinese days are bright, I have to pay close attention to sleep, I hope you can help me. One night did not sleep

**Comment by vforteli** [comment]
Cant really help much with that error. Just make sure the dictionary file is copied to output, and is readable by the process.

**Comment by bbhxwl** [comment]
I found this to be a bug that requires an incoming file that is not a folder. Will not you modify the normal operation?

**Comment by vforteli** [comment]
Its not a bug, but depends on how you reference RadiusServer. If you build it and create an assembly reference to the dll, Visual Studio doesnt know about the directory file and wont copy it to the output.
However, if you put the projects in the same solution and create a project reference, Visual Studio should copy the file to the final output directory.
